### ISSUE TITLE
MapperParsingException

### ISSUE THREAD

**Issue by Laazarus** [matrus2/dynamodb-stream-elasticsearch#14]
Hello,

I am trying your library but every time I perform an operation on the DB I am getting the following error:
```
"errorType": "Error",
    "errorMessage": "Error Error: MapperParsingException[object mapping for [lesson] tried to parse field [description] as object, but got EOF, has a concrete value been provided to it?] :: {\"path\":\"/language/lesson/156f7a4b-91b8-4bbb-bdb8-7085a344894e\",\"query\":{\"refresh\":\"true\",\"timeout\":\"5m\"},\"body\":\"{\\\"description\\\":\\\"Micia miao del gatto\\\",\\\"lessonId\\\":\\\"156f7a4b-91b8-4bbb-bdb8-7085a344894e\\\",\\\"language\\\":\\\"en-GB\\\",\\\"video\\\":\\\"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4\\\",\\\"title\\\":\\\"Micia theory\\\",\\\"type\\\":\\\"lessons\\\",\\\"tags\\\":[\\\"it\\\",\\\"games\\\",\\\"videogames\\\",\\\"software\\\",\\\"friendship\\\"]}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":\\\"MapperParsingException[object mapping for [lesson] tried to parse field [description] as object, but got EOF, has a concrete value been provided to it?]\\\",\\\"status\\\":400}\"}",
    "stack": [
        "Error: Error Error: MapperParsingException[object mapping for [lesson] tried to parse field [description] as object, but got EOF, has a concrete value been provided to it?] :: {\"path\":\"/language/lesson/156f7a4b-91b8-4bbb-bdb8-7085a344894e\",\"query\":{\"refresh\":\"true\",\"timeout\":\"5m\"},\"body\":\"{\\\"description\\\":\\\"Micia miao del gatto\\\",\\\"lessonId\\\":\\\"156f7a4b-91b8-4bbb-bdb8-7085a344894e\\\",\\\"language\\\":\\\"en-GB\\\",\\\"video\\\":\\\"http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4\\\",\\\"title\\\":\\\"Micia theory\\\",\\\"type\\\":\\\"lessons\\\",\\\"tags\\\":[\\\"it\\\",\\\"games\\\",\\\"videogames\\\",\\\"software\\\",\\\"friendship\\\"]}\",\"statusCode\":400,\"response\":\"{\\\"error\\\":\\\"MapperParsingException[object mapping for [lesson] tried to parse field [description] as object, but got EOF, has a concrete value been provided to it?]\\\",\\\"status\\\":400}\"}",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:51)",
        "    at callback (/var/runtime/CallbackContext.js:40:7)",
        "    at /var/runtime/CallbackContext.js:103:16",
        "    at i.then.catch.e (/var/task/src/elastic_search/handler.js:9:261565)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}

Thanks in advance for the help and the library :)

**Comment by matrus2** [comment]
Hi,

Could you add here the structure of object, which you try to parse?
For instance:
`  Records: [
    {
      eventID: 'bc87af2e29e12f293d5e4f5d5d7e2e0a',
      eventName: 'MODIFY',
      eventVersion: '1.1',
      eventSource: 'aws:dynamodb',
      awsRegion: 'eu-central-1',
      dynamodb: {
        ApproximateCreationDateTime: 1548519006,
        Keys: {
          id: {
            S: '12'
          }
        },
        NewImage: {
          number: {
            N: '123'
          },
          nbset: {
            NS: ['12']
          },
          data: {
            M: {
              '12': {
                BS: ['YWRzYQ==', 'dGVzdCE=']
              },
              first: {
                S: 'first'
              }
            }
          },
          strset: {
            SS: ['asd', 'asdasd']
          },
          adress: {
            M: {
              city: {
                S: 'Warsaw'
              },
              details: {
                M: {
                  street: {
                    S: 'Avenue'
                  },
                  num: {
                    N: '123'
                  },
                  clientIds: {
                    SS: ['12', '123', '345']
                  }
                }
              },
              locations: {
                L: [
                  {
                    M: {
                      city: {
                        S: 'Wro'
                      }
                    }
                  },
                  {
                    M: {
                      city: {
                        S: 'Wro2'
                      }
                    }
                  }
                ]
              }
            }
          },
          id: {
            S: '12'
          },
          list: {
            L: [
              {
                B: 'dGVzdCE='
              }
            ]
          }
        },
        OldImage: {
          number: {
            N: '123'
          },
          nbset: {
            NS: ['12']
          },
          data: {
            M: {
              '12': {
                BS: ['YWRzYQ==', 'dGVzdCE=']
              },
              first: {
                S: 'first'
              }
            }
          },
          strset: {
            SS: ['asd', 'asdasd']
          },
          id: {
            S: '12'
          },
          list: {
            L: [
              {
                B: 'dGVzdCE='
              }
            ]
          }
        },
        SequenceNumber: '11844300000000003688488011',
        SizeBytes: 267,
        StreamViewType: 'NEW_AND_OLD_IMAGES'
      },
      eventSourceARN:
        'arn:xxx'
    }
  ]
}`

**Comment by Laazarus** [comment]
Hey, thanks for answering so fast:

This is the record the library receives :+1: 
```
{
    "Records": [
        {
            "eventID": "657fbdedceb44b1faeab81710496a222",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "eu-west-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1560268825,
                "Keys": {
                    "lessonId": {
                        "S": "156f7a4b-91b8-4bbb-bdb8-7085a344894e"
                    }
                },
                "NewImage": {
                    "description": {
                        "S": "Micia miao del gatto"
                    },
                    "lessonId": {
                        "S": "156f7a4b-91b8-4bbb-bdb8-7085a344894e"
                    },
                    "language": {
                        "S": "en-GB"
                    },
                    "video": {
                        "S": "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"
                    },
                    "title": {
                        "S": "Micia theory"
                    },
                    "type": {
                        "S": "lessons"
                    },
                    "tags": {
                        "L": [
                            {
                                "S": "it"
                            },
                            {
                                "S": "games"
                            },
                            {
                                "S": "videogames"
                            },
                            {
                                "S": "software"
                            },
                            {
                                "S": "friendship"
                            }
                        ]
                    }
                },
                "SequenceNumber": "4633900000000014748988905",
                "SizeBytes": 293,
                "StreamViewType": "NEW_IMAGE"
            },
            "eventSourceARN": "arn:aws:dynamodb:eu-west-1:092874714154:table/dev_LessonsTable/stream/2019-06-10T13:55:42.216"
        }
    ]
}

**Comment by Laazarus** [comment]
Hey I found out what was wrong sorry,

It is that I had initialised my Elastic search with a lambda that was not managed by your package.

After a bit I found your solution and I wanted to use it but evidently my old data was conflicting with your logic.

I deleted my old index and created a new you and it works.

Sorry to have wasted your time your library works just fine apparently :D
