### ISSUE TITLE
Async / await

### ISSUE THREAD

**Issue by dawez** [matrus2/dynamodb-stream-elasticsearch#15]
Is it possible to pass a function that returns a promise as "transform" function?

i.e. my use case would be that the stream is called when table1 get a change. I would have need also some data from table2 to augment the results in ES.

Table2 fetching requires an async operation. For example this one would be an async function as transformer.

```
 const transform = async (body:) => {
    constotherId = body.otherId;
    const otherObject = await PersistedObject.findWithId(otherId);
    return { ...body, extraProperty: otherObject.name };
  };
```

**Comment by matrus2** [comment]
Every good point, I will implement this asap (this week the latest)
