### ISSUE TITLE
modify items for reordering

### ISSUE THREAD

**Issue by Laazarus** [matrus2/dynamodb-stream-elasticsearch#17]
Hello, 
First of all thanks for the library, it is a month that I am using it and it is really great.

Now I have a problem that is more an issue with ES rather than a problem with the library (once again thanks so much).

The problem is that sending the info to ES in a basic way ES brake the fields in many parts and makes the ordering almost useless. I have a bit of problem also with the search because I would love to perform partial searches with the wildcard * so If I have a user John Done I can search Joh and I will find, along with others, John Doe.
I was reading this link

https://stackoverflow.com/questions/34493947/elasticsearch-is-not-sorting-the-results

And it seems a nice solution, I know that this library supports a transform function so I imagine I could do this operation there?
Adding fields to the object in order to make the ordering easier? 
Any suggestion on how to enable the wildcard too?

Thanks again for the help and the fantastic library

**Comment by matrus2** [comment]
Thanks for using this package. I think transform is a way to go and you need separately change mappings as described in the thread you provided, but honestly in case of troubles you should ask better es expert then me.

**Comment by Laazarus** [comment]
Thanks for the explanation 

I thought this was such a common issue that you might have it sorted already.

I am trying to use the transform as described in the doc but I cannot get it to work;

does it have to return a promise?

If you have any example there to use would be great.

Do you have any example?

Best Regards

Nic

**Comment by matrus2** [comment]
See integration tests. There are two types of transform function one for Promise and one for non Promise.

**Comment by matrus2** [comment]
Pls ensure you use proper version of package.

**Comment by Laazarus** [comment]
Thank you so much!!

I will have a look now because it seems I cannot get it to be called

**Comment by Laazarus** [comment]
So I have checked the documentation and the solution I am trying is to detect if the index is created and if it is not existing yet then I create the index and send the configuration mapping I want for the object.

The problem is that is I fo so the library does not write the item in anymore:
this is the code I am trying:
```
const res = await axios.get(`${ES_ENDPOINT}/${index}`, {
      validateStatus: function (status) {
        console.log("status is ", status);
        return status == 200 || status == 404;
      }
    });
    console.log("result for existance", res);
    if (res.status == 404) {
      try{
      await axios.put(
        `${ES_ENDPOINT}/${index}`,
        Settings
      );
      console.log('MAPPINGS for index',JSON.stringify(MAPS[`${index}_index`]))
      await axios.put(
        `${ES_ENDPOINT}/${index}`,
        MAPS[`${index}_index`]
      );

As you can see first I check if the index exists if does not exists (I get a 404) I create it and I set its mapping.

The mapping for index assets is :
```mappings: {
      "dynamic": true,
      document: {
        "properties": {
          title: {
            type: "string", "analyzer": "autocomplete", "search_analyzer": "standard",
            fields: {
              raw: {
                type: "string",
                index: "not_analyzed"
              }
            }
          }
        }
      }
    }`

Do you know if this causes any problem for your library? Do you know how I can set the mapping to my object without interfering with your library?

Thank you very much again

**Comment by Laazarus** [comment]
I have fixed the issue,

The problem was with the call back function
