### ISSUE TITLE
Typescript refactor / DefinitelyTyped

### ISSUE THREAD

**Issue by cobraz** [matrus2/dynamodb-stream-elasticsearch#19]
Hello 👋

I’d like to look into refactoring or providing some definitions to this library. Okey, so I’ve been using this for a good while now, and I’m super happy with it! One benefit is that it just works, and I just drop the thing into a Lamda function and of we go.

Recently, the industry has praised (IMHO) TypeScript and we’ve seen many projects having it. I don’t think that alone makes a reason to refactor this project, but the fact that we are now seeing Pulumi. It utilizes TypeScript to define infrastructure, and this project can be an essential tools to make that experience as best as it can be.

I would be happy to rough out a starting point for the refactor (keeping the current API, or course), but before I do, I would like to check with any developers that find this issue (maybe searching for types to the library) and the maintainers. Should we do any of this? What other gains are there? What about pitfalls?

**Comment by matrus2** [comment]
For now the easiest would be to add `index.d.ts` with proper types definition. In the future there is a plan  do some refactor, but this require coordination.
