### ISSUE TITLE
Upgrading Elasticsearch client

### ISSUE THREAD

**Issue by mstn** [matrus2/dynamodb-stream-elasticsearch#22]
This package is based on a soon deprecated [version](https://www.npmjs.com/package/elasticsearch) of elasticsearch official client. Do you have any plan for migration? Do you accept PRs?

**Comment by matrus2** [comment]
Hi, 
Thanks for the comment. Yep, the version should be updated (but then I would go with major version release) and yes I accept the PRs.

**Comment by mstn** [comment]
Hi @matrus2, there you go https://github.com/matrus2/dynamodb-stream-elasticsearch/pull/23. Let me know if you need changes!
