### ISSUE TITLE
mapper_parsing_exception

### ISSUE THREAD

**Issue by edgehero** [matrus2/dynamodb-stream-elasticsearch#31]
Love using your libary. but i hit a problem that i am not able to solve. 

im trying to push a simple dymanodb stream to elasticsearch. 

running elasticsearch 7.1
but im getting a error, how can i solve this problem?

error:
`
ResponseError: mapper_parsing_exception
    at IncomingMessage.<anonymous> (/var/task/node_modules/@elastic/elasticsearch/lib/Transport.js:232:25)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  meta: {
    body: { error: [Object], status: 400 },
    statusCode: 400,
    headers: {
      date: 'Thu, 27 Aug 2020 17:01:06 GMT',
      'content-type': 'application/json; charset=UTF-8',
      'content-length': '457',
      connection: 'keep-alive',
      'access-control-allow-origin': '*'
    },
    warnings: null,
    meta: {
      context: null,
      request: [Object],
      name: 'elasticsearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  }
} 
{
    "Records": [
        {
            "eventID": "f528a40a996f0952a9a99902b902d98c",
            "eventName": "INSERT",
            "eventVersion": "1.1",
            "eventSource": "aws:dynamodb",
            "awsRegion": "eu-west-1",
            "dynamodb": {
                "ApproximateCreationDateTime": 1598547664,
                "Keys": {
                    "id": {
                        "S": "e5271750-5933-42ad-8d0c-d6ba75676067"
                    }
                },
                "NewImage": {
                    "changeDate": {
                        "S": "2020-08-27T17:01:04.240Z"
                    },
                    "description": {
                        "S": "wow23"
                    },
                    "id": {
                        "S": "e5271750-5933-42ad-8d0c-d6ba75676067"
                    },
                    "title": {
                        "S": "me3"
                    },
                    "type": {
                        "S": "request"
                    },
                    "createDate": {
                        "S": "2020-08-27T17:01:04.240Z"
                    },
                    "status": {
                        "S": "active"
                    },
                    "tags": {
                        "L": [
                            {
                                "S": "#test"
                            }
                        ]
                    }
                },
                "SequenceNumber": "15241300000000009393215864",
                "SizeBytes": 204,
                "StreamViewType": "NEW_AND_OLD_IMAGES"
            },
            "eventSourceARN": "arn:aws:dynamodb:eu-west-1:990669775596:table/Request-gitwanted-api-dev/stream/2020-08-24T10:45:06.825"
        }
    ]
}
`

**Comment by Jotakuun** [comment]
I'm having the same error...
