### ISSUE TITLE
Always times out when used with AWS Lambda

### ISSUE THREAD

**Issue by jakelauer** [matrus2/dynamodb-stream-elasticsearch#32]
I'm no Lambda expert, but I believe I have configured everything correctly according to the instructions provided.

My environment variables:

ES_ENDPOINT | https://my-endpoint-url.us-west-2.es.amazonaws.com
-- | --
INDEX | highlights-index
TYPE | Highlights

And the logs:

```
2020-10-14T12:11:23.449-07:00 | 2020-10-14T19:11:23.449Z c4a28f98-ebb0-45ec-83bc-6fa20da6035b INFO Received event: 10 Records
-- | --
  | 2020-10-14T12:11:53.472-07:00 | END RequestId: c4a28f98-ebb0-45ec-83bc-6fa20da6035b
  | 2020-10-14T12:11:53.472-07:00 | REPORT RequestId: c4a28f98-ebb0-45ec-83bc-6fa20da6035b Duration: 30029.74 ms Billed Duration: 30000 ms Memory Size: 1088 MB Max Memory Used: 38 MB
  | 2020-10-14T12:11:53.472-07:00 | 2020-10-14T19:11:53.471Z c4a28f98-ebb0-45ec-83bc-6fa20da6035b Task timed out after 30.03 seconds
```

**Comment by aterreno** [comment]
@jakelauer I doubt it's a problem with this library, it's possible that you can't reach the ES endpoint from your lambda. 
That might happen if you are in a VPC without a NAT gateway that lets you call out. 

Or a simple misconfiguration of the endpoint, you need to double-check that everything works first. 

I'd start with a hello world doing a simple ping from the elastic search client, or even better just use request and do that call from there. No libraries, no frameworks, no complexity.
