### ISSUE TITLE
useBulk uses the wrong value for refresh

### ISSUE THREAD

**Issue by ChristerGustavsson** [matrus2/dynamodb-stream-elasticsearch#40]
When using `useBulk: true` together with `refresh: false` still sends `?refresh=true` in the bulk request.

This was observed in version 2.10.0 and looks like the error still exist on: https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/6b1d1dfb59f1dd088e65ae1b87146c8ec5500880/src/index.js#L98, setting the wrong key `toUpsert` instead of `refresh`.

I tried to start a PR but I get version conflicts when attempting to install the node modules, which is to be honest too much context for me to delve into right now so I'm hoping just opening an issue is okay.

```dynamodb-stream-elasticsearch on  master is 📦 v3.0.0 via  v15.14.0
at 12:45:30 ❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: dynamodb-stream-elasticsearch@3.0.0
npm ERR! Found: @elastic/elasticsearch@7.10.0
npm ERR! node_modules/@elastic/elasticsearch
npm ERR!   @elastic/elasticsearch@"7.10.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @elastic/elasticsearch@">=5.6.16 <=7.9.1" from @acuris/aws-es-connection@2.1.0
npm ERR! node_modules/@acuris/aws-es-connection
npm ERR!   @acuris/aws-es-connection@"2.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by matrus2** [comment]
Hi @ChristerGustavsson,

You can notice that few lines above there is:
```toUpsert.push({ index, id, body, refresh })```
so the flag is set correctly. If you run tests you will find that:
```js
  elasticsearch Starting a new request {
  method: 'POST',
  path: '/_bulk',
  bulkBody: [ { delete: [Object] } ],
  querystring: 'refresh=false',
  body: '{"delete":{"_index":"test","_id":"russ-wintheiser-c240e6ac-3"}}\n',
  headers: {
    'user-agent': 'elasticsearch-js/7.7.1 (darwin 20.2.0-x64; Node.js v14.15.3)',
    'content-type': 'application/x-ndjson',
    'content-length': '64'
  },
  timeout: 30000
} +154ms
```

Closing.

**Comment by ChristerGustavsson** [comment]
That test you did seems to be for delete not upserts, and that looks fine and uses the correct key for es.bulk: https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/6b1d1dfb59f1dd088e65ae1b87146c8ec5500880/src/index.js#L77

But if you look for upset es.bulk: https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/6b1d1dfb59f1dd088e65ae1b87146c8ec5500880/src/index.js#L98

**Comment by matrus2** [comment]
Right, I put a wrong test example. Looking a that code bulk uses correct value for refresh:
https://github.com/matrus2/dynamodb-stream-elasticsearch/blob/master/src/index.js#L62

**Comment by ChristerGustavsson** [comment]
That line you linked to pushed the correct value to the `toUpsert` array, sure. Which is used with `toUpsert[0].refresh` - so yeah that looks fine. But, like I've tried to explain a few times now it looks like it uses the wrong key when passed along to es.bulk:

![Screenshot 2021-05-03 at 12 17 10](https://user-images.githubusercontent.com/894998/116865483-05175e00-ac0a-11eb-9ba3-970193ed6dd5.png)
