### ISSUE TITLE
Serverless Webpack bundle size

### ISSUE THREAD

**Issue by tobeycodes** [matrus2/dynamodb-stream-elasticsearch#43]
Hello,

Thanks for this package it works great.

I am having some issues with the Serverless Framework when building the Lambda function with Webpack it creates a 20MB artefact. AWS SDK is included in Lambda and it is not something that we need to directly have as a dependency. It is still needed for testing but it should be possible that packages exclude it from the artefact when deploying with Webpack.

There is a related issue here https://github.com/serverless-heaven/serverless-webpack/issues/292

Their solution is to use `peerDependencies `

```
The most correct way is, that modules that require the aws-sdk define them as peerDependencies. So the le-* dependencies should have aws-sdk as peerDependency, which in turn requires the using module (your service) to have it as either "devDependecy" or "dependency" to fulfill the requirement.
Then the forceExclude will work as expected.
This is the same as with serverless-webpack and the webpack dependency.
As long as the modules have the sdk in their production dependencies it could additionally come to version conflicts and even duplications of the aws-sdk.
```

How would you feel about this change?

**Comment by matrus2** [comment]
Hi, will check.
