### ISSUE TITLE
Not being able to configure auth without aws credentials

### ISSUE THREAD

**Issue by GrigoreMihai** [matrus2/dynamodb-stream-elasticsearch#48]
We have a cluster which is configured to use an user and password for authentication.  In the previous versions of your package we were able to use it by using the `testMode` constant. eg: 

```javascript
 pushStream( { event, endpoint: "https://" + ES_DOMAIN, testMode:true, index: "dynamodb-sources", type: "dynamo", transformFunction: modifyRecord, useBulk:true, 
        elasticSearchOptions: {auth: {
            username: ES_USER,
            password: ES_PASS
        } }   
    } )
```

In this commit this flag is removed:  https://github.com/matrus2/dynamodb-stream-elasticsearch/commit/c99e008750520a3c3dd7d12b16c84b9da443fc2f#diff-ac1fa144d8a26929871e9bd0a2dc01736ee07d205abedd47bf638c69907fdfd7R8 .

It would be nice to have still have some flag that will allow to skip the default `AWSConnection` and connect using the user and password authentication.

**Comment by tong-bluehill** [comment]
I got same issue. I rollback to v3.0.2. It works now.
