### ISSUE TITLE
Some digits are missing when there is a large number in the N field of a DynamoDB record.

### ISSUE THREAD

**Issue by makotok** [matrus2/dynamodb-stream-elasticsearch#49]
The Elasticsearch Long field supports 64-byte signed integers.

https://www.elastic.co/guide/en/elasticsearch/reference/7.16/number.html

For example, I stored the following large integer in DynamoDB from a Java application, and after DynamoDB Streams was started, when Lambda using this library processed the record, some digits were missing as shown below. The document is saved in Elasticsearch.

- DynamoDB: 3804086584686624768
- Elasticsearch: 3804086584686625000

This happens because the DynamoDB record is converted to the JavaScript Number type when it is unmarshalled.

The integer part of type Number only supports integers up to 53 bits (9007199254740991 to be exact), so if this value is exceeded, it will be rounded.

**Comment by matrus2** [comment]
Hi @makotok,

Thanks for rising this one. After all I thing the issue is not with this library, but with the  `AWS.DynamoDB.Converter.unmarshall` function itself. Most probably it should be submitted there, unless you see different option.

Thx

**Comment by makotok** [comment]
@matrus2 
Thank you for your reply.

Library users can pass options to the AWS.DynamoDB.Converter.unmarshall function.

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/Converter.html#unmarshall-property

* wrapNumbers ... Whether to return numbers as a NumberValue object instead of converting them to native JavaScript numbers. This allows for the safe round-trip transport of numbers of arbitrary size.

Ideally, I think it's better to use this option.
Next, in the case of NumberValue, it would be nice to be able to choose whether to convert to a String. (Alternatively, library users should be able to handle this with the transformFunction function)

However, I have to take the option of not using Lambda, so for now you don't have to fix this issue.
