### ISSUE TITLE
Getting Authorization Exception

### ISSUE THREAD

**Issue by harleyguru** [matrus2/dynamodb-stream-elasticsearch#6]
Hello,

At first, Thanks for your good job and I'd like to use this module to load our DDB data to Amazon ES service.

But I am getting this error log in CloudWatch:
```
{
    "errorMessage": "Authorization Exception :: {\"path\":\"/fliphire/application/060aeb59-d120-4160-a365-ef1aaeb34f503bb9bfb0-8ff7-40a5-9c52-35210683a18d\",\"query\":{\"refresh\":true},\"statusCode\":403,\"response\":\"\"}",
    "errorType": "Error",
    "stackTrace": [
        "exports.pushStream (/var/task/node_modules/dynamodb-stream-elasticsearch/src/index.js:41:17)",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}
```

Here is my code snippet how I am using your library:
```
'use strict';

/**
 * Lambda trigger for DDB table stream to load data from DDB to ES
 */

const { pushStream } = require('dynamodb-stream-elasticsearch');

const { ES_ENDPOINT, INDEX } = process.env;

module.exports.handler = async event => {
  console.log(JSON.stringify(event));

  try {
    await pushStream({ event, endpoint: ES_ENDPOINT, index: INDEX, type: 'application' });
    console.log(`Successfully processed ${event.Records.length} records.`);
  } catch (error) {
    console.error(`${error}`);
    throw error;
  }
};
```

Can you help me why I am getting this?

Thanks

**Comment by harleyguru** [comment]
I am using node.js 8.10 and we are building DDB as main data source but trying to load data to ES for better performance.

we are deploying via serverless framework and assigning right IAM role to this lambda function so that it can access to ES service.

I am wondering if this happens because of signing requests via Signature V4?

**Comment by matrus2** [comment]
Hey, most probably you are right. Your ES domain may require signed requests. I will try to investigate this issue in the future, but it may take some time :) In the meantime I encourage you to open a PR, which can handle such requests. 
Here is the suggestion of how to handle this:

https://github.com/aws-samples/amazon-elasticsearch-lambda-samples/blob/master/src/kinesis_lambda_es.js#L52

**Comment by harleyguru** [comment]
Thanks @matrus2 I've solved the issue myself.

The root cause was IAM policy I was assigning to my lambda function.
After I set right permission so that my lambda can access to ES, it's working great.

Thanks again. I love to use this library

**Comment by matrus2** [comment]
@harleyguru Thanks,for the replay.

Could you copy/paste here your policy (of course only part regarding lambda and ES) so if somebody came across the same issue he can solve it easily.
Thx in advance.

**Comment by harleyguru** [comment]
Yeah, This is snippet of my serverless.yml config doing it:
```
iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - es:*
      Resource:
        - '*'
```

Earlier, I was using specific value for Resource, but now I am using wildcard to allow access for everything.

Because I am using your library in AWS Lambda environment, my lambda function will get credentials based on this permission.
