### ISSUE TITLE
[Suggestion] Opportunity to choose which fields to send to ElasticSearch

### ISSUE THREAD

**Issue by igolskyi** [matrus2/dynamodb-stream-elasticsearch#8]
Hello @matrus2 . Thank you for your code. Could you add the opportunity to choose which fields to send to ElasticSearch (from Lambda)? That is,  ability write to ElasticSearch some fields from the object of Image Stream.

**Comment by matrus2** [comment]
Added to todo list.

**Comment by cdelgadob** [comment]
@matrus2 , What's your approach here? What I would do here is to accept a function as optional parameter which would do the transformation/filtering process of each record.
This way you can not only choose which fields go to ES, but also add fields for improve indexing etc...

**Comment by cdelgadob** [comment]
Created a PR for this issue, please review #13 

Thanks
