### ISSUE TITLE
[Suggestion] add credencials to config

### ISSUE THREAD

**Issue by igolskyi** [matrus2/dynamodb-stream-elasticsearch#9]
Could you add the opportunity to set config options not only `endpoint`, but and `credentials` like this https://stackoverflow.com/a/53708779/6011421 (from Lambda)?

Temporarily, I ported a part of the code from node_modules to lambda to be able to configure the ElasticSearch parameters. Hope to improve your code.

![image](https://user-images.githubusercontent.com/22115961/49746275-87a1ca80-fca9-11e8-8c21-f1803ceb3105.png)

**Comment by matrus2** [comment]
Add to todo list,
